config/routes.rb
Rails.application.routes.draw do
  root to: "main#index"

  get "/blog", to: "blogs#new"
  post "/blog", to:"blogs#create"

  get "/sign_up", to:"registrations#new"
  post "/sign_up", to:"registrations#create"
  delete "/logout", to:"sessions#destroy"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/user.rb
# email: string
# password_digest: string
#
#password: string virtual
#password_confirmation: string virtual

class User < ApplicationRecord
    has_secure_password

    validates :email, presence: true, format: {with: /\A[^@\s]+@[^@\s]+\z/}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user

    def set_current_user
      if session[:user_id]
        Current.user = User.find_by(id: session[:user_id])
      end
    end  
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
    def new
        @blog = Blog.new
    end

    def create
        # blog param = {:title => "test string", :body=>"demo"}
        @blog = Blog.new(blog_param)
        if @blog.save
            redirect_to "/", notice: "Successfully saved the blog!"
        else
            render :new
        end
    end

    private

    def blog_param
        params.require(:blog).permit(:title, :body)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
        flash[:alert] = "This is an alert to test flash [built in hashmap, like cache] in ruby!"
        @blogs = Blog.all
        @user = User.find_by(id: session[:user_id])
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    def new
        @user = User.new
    end
    def create
        @user = User.new(user_param)
        if @user.save
            session[:user_id] = @user.id
            redirect_to "/", notice: "User saved sucessfully!"
        else
            render :new
        end
    end

    private
    
    def user_param
        params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged out"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blogs/new.html.erb
<h1 class="mb-4 mt-4">New Blog</h1>

<%= form_with model: @blog, url: blog_path do |form|%>
    <div class="mb-3">
        <%= form.label :title%>
        <%= form.text_field :title, class: "form-control", placeholder: "Title of the blog..."%>
    </div>
    <div class="mb-3">
        <%= form.label :body%>
        <%= form.text_area :body, class:"form-control"%>
    </div>

    <div>
        <%=form.submit "Post a Blog", class:"btn btn-primary"%>
    </div>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# adding bootstrap cdn to the project %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"/>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" defer>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial:"shared/navbar" %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<%= render partial:"shared/flash"%>
<h1 class="d-flex justify-content-center mt-4">Sabbir's Blog</h1>

<div class="d-flex justify-content-evenly mt-5">
    <% @blogs.each do |blog| %>
        <div class="card" style="width: 18rem;">
            <%= image_tag("demo-mg.jpg", class:"card-img-top") %>
            <div class="card-body">
                <h5 class="card-title"><%= blog.title%></h5>
                <p class="card-text"><%= blog.body %></p>
            </div>
        </div>
    <%end%>
</div>

app/views/shared/_flash.html.erb
<%
=begin%>
 <% if flash[:alert]%>
    <div class="alert alert-info mt-4" role="alert">
        <%= flash[:alert]%>
    </div>
<%end%> 
<%
=end%>

<%if flash[:notice]%>
    <div class="alert alert-success mt-4">
        <%= flash[:notice]%>
    </div>
<%end%>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">MyBlogs</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/blog">Write</a>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if Current.user %>
          <li class="nav-item">
            <span class="navbar-text"><%= Current.user.email %></span>
          </li>
          <%= button_to "Logout", logout_path, method: :delete, class:"btn btn-sm btn-outline-secondary" %>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", sign_up_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>